name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main  # Trigger only on push to main

jobs:
  deploy:
    name: Deploy to EKS Cluster
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Configure AWS credentials
      - name: Configure AWS Credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws-region: ${{ secrets.AWS_REGION }}  # ✅ THIS IS REQUIRED


      # 3. Set up kubectl to interact with EKS
      - name: Set up kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      # 4. Optional: Build your Docker image and push to ECR (if needed)
      # - name: Build and push Docker image
      #   run: |
      #     docker build -t myapp:latest .
      #     docker tag myapp:latest <your ECR repo URL>:latest
      #     docker push <your ECR repo URL>:latest

      # 5. Apply Kubernetes manifests
      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f k8s/

      # 6. Verify deployment
      - name: Wait for Deployment to Finish
        run: |
          kubectl rollout status deployment/your-deployment-name -n default
